package seigneur.gauvain.mycourt.data.api

/**
 * CAREFUL :
 * This class integrates client id and secret generated by Dribble,
 * It should not be committed and must be keep secret !
 */
object DribbbleClient {
    const val CLIENT_ID = "154eea1239738ef824e61bdc8ebd82f40da4a0e7dfd0731dca67707128b8b884"
    const val CLIENT_SECRET = "06d4a33c2fe4b300da69b54698a1013b6a2ac9774b6133c8d4c5149e701572a7"
}
